### ISSUE TITLE
Can I share states across multiple nginx workers?

### ISSUE THREAD

**Issue by yangyuqian** [matsumotory/mruby-userdata#1]
Hi, @matsumoto-r 

I'm working with the mruby module recently and need to share some data across different context(http/location).

This gem is very helpful, thank you for doing this.

But can I share data across different nginx workers?

**Comment by matsumotory** [comment]
@yangyuqian Sorry for my late response. mruby-userdata can't shared the object between workers. So you should use file-based or external data store like mruby-vedis, mruby-memcached, mruby-localmemcache or mruby-redis.
